before_script:
  - uname -r
  - pwd
  - meteor node --version
  - meteor npm --version
  - export PROJECTFILE="mantraboilerplate.tar.gz"
  - export FOLDER="/home/snapzio/mantraboilerplate/"
  - bash version.sh > private/version.json;

cache:
  paths:
    - .meteor/local/
    - node_modules/

Dev:
  only:
    - dev
  script:
    - npm install;
    - eslint .
    - meteor build . --server-only;
    - find $FOLDER -mindepth 1 -delete;
    - rsync -av $PROJECTFILE $FOLDER;
    - cd $FOLDER; tar -xf $PROJECTFILE; cd bundle/programs/server; npm install --production; chown -R snapzio:www-data .; service nginx reload;
