before_script:
  - shopt -s expand_aliases
  - uname -r
  - pwd
  - meteor node --version
  - meteor npm --version
  - export PROJECTFILE="mantraboilerplate.tar.gz"
  - export FOLDER="/home/snapzio/mantraboilerplate/"
  - bash version.sh > private/version.json;
  - alias time="/usr/bin/time -f 'Took %e seconds'"

cache:
  paths:
    - .meteor/local/
    - node_modules/

Dev:
  only:
    - dev
  script:
    - time nsp check --output summary
    - time npm install;
    - time eslint .
    - time meteor build . --server-only;
    - time find $FOLDER -mindepth 1 -delete;
    - time rsync -av $PROJECTFILE $FOLDER;
    - time cd $FOLDER; tar -xf $PROJECTFILE; cd bundle/programs/server; npm install --production; chown -R snapzio:www-data .; service nginx reload;
