before_script:
  - export PROJECTUSER="snapzio"
  - export PROJECTFOLDER="/home/snapzio/mantraboilerplate"
  - export PROJECTFILES="mantraboilerplate.tar.gz"
  - export DEVSERVER="app1.snapzio.com"
  - pwd
  - shopt -s expand_aliases
  - alias time="/usr/bin/time -f 'Took %e seconds'"

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true

build:
  stage: build
  only:
    - dev
    - prod
  script:
    - time npm install;

test:
  stage: test
  only:
    - dev
    - prod
  script:
    - time eslint .
    - time npm run test
    - time npm run gagarin-build

dev-deploy:
  stage: deploy
  environment: dev
  only:
    - dev
  script:
    - time npm run version;
    - time meteor build . --server-only;
    - time ssh $DEVSERVER "find $PROJECTFOLDER -mindepth 1 -delete";
    - time rsync -av $PROJECTFILES $DEVSERVER:$PROJECTFOLDER;
    - time ssh $DEVSERVER "cd $PROJECTFOLDER && tar -xf $PROJECTFILE && cd bundle/programs/server && meteor npm install --production && chown -R $PROJECTUSER:www-data $PROJECTFOLDER && passenger-config restart-app $PROJECTFOLDER";
