before_script:
  - export PROJECTUSER="snapzio"
  - export PROJECTFOLDER="/home/snapzio/mantraboilerplate"
  - export PROJECTFILES="mantraboilerplate.tar.gz"
  - export DEVSERVER="app1.snapzio.com"
  - export PRODSERVER="app1.rometic.com"
  - pwd
  - shopt -s expand_aliases
  - alias time="/usr/bin/time -f 'Took %e seconds'"

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true

build:
  stage: build
  only:
    - dev
    - prod
  script:
    - time npm install;

test:
  stage: test
  only:
    - dev
    - prod
  script:
    - time eslint .
    - time npm run test
    - time npm run gagarin-build

dev:
  stage: deploy
  environment: dev
  only:
    - dev
  script:
    - time npm run version;
    - time meteor build . --server-only;
    - time find $PROJECTFOLDER -mindepth 1 -delete;
    - time rsync -av $PROJECTFILES $PROJECTFOLDER;
    - cd $PROJECTFOLDER && tar -xf $PROJECTFILES && cd bundle/programs/server && meteor npm install --production && chown -R $PROJECTUSER:www-data . && passenger-config restart-app $PROJECTFOLDER;
