before_script:
  - shopt -s expand_aliases
  - uname -r
  - pwd
  - meteor node --version
  - meteor npm --version
  - alias time="/usr/bin/time -f 'Took %e seconds'"
  - export PROJECTFILE="mantraboilerplate.tar.gz"
  - export PROJECTFOLDER="/home/snapzio/mantraboilerplate/"
  - export PROJECTUSER="snapzio"

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules/

all-build:
  stage: build
  script:
    - time npm install;

all-test:
  stage: test
  script:
    - time eslint .
    - time npm run test
    - time npm run gagarin-build

dev-deploy:
  stage: deploy
  only:
    - dev
  script:
    - export SETTINGS="dev";
    - time npm run version;
    - time meteor build . --server-only;
    - time find $PROJECTFOLDER -mindepth 1 -delete;
    - time rsync -av $PROJECTFILE $FOLDER;
    - cd $FOLDER && tar -xf $PROJECTFILE && cd bundle/programs/server && meteor npm install --production && chown -R $PROJECTuser:www-data . && service nginx reload;
