before_script:
  - shopt -s expand_aliases
  - uname -r
  - pwd
  - meteor node --version
  - meteor npm --version
  - export PROJECTFILE="mantraboilerplate.tar.gz"
  - export FOLDER="/home/snapzio/mantraboilerplate/"
  - bash version.sh > private/version.json;
  - alias time="/usr/bin/time -f 'Took %e seconds'"

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true

build:
  stage: build
  script:
    - time npm install;

test:
  stage: test
  script:
    - time eslint .
    - time npm run test
    - time npm run gagarin-build

deploy-dev:
  stage: deploy
  only:
    - dev
  script:
    - time meteor build . --server-only;
    - time find $FOLDER -mindepth 1 -delete;
    - time rsync -av $PROJECTFILE $FOLDER;
    - cd $FOLDER && tar -xf $PROJECTFILE && cd bundle/programs/server && meteor npm install --production && chown -R snapzio:www-data . && service nginx reload;
