before_script:
  - shopt -s expand_aliases
  - uname -r
  - pwd
  - meteor node --version
  - meteor npm --version
  - alias time="/usr/bin/time -f 'Took %e seconds'"
  - export PROJECTFILE="mantraboilerplate.tar.gz"
  - export PROJECTFOLDER="/home/snapzio/mantraboilerplate"
  - export PROJECTUSER="snapzio"

build:
  stage: build
  script:
    - time npm install
  artifacts:
    paths:
    - node_modules/

test:
  stage: test
  script:
    - time eslint .
    - time npm run test
    - time npm run gagarin-build

dev:
  stage: deploy
  only:
    - dev
  script:
    - time npm run version;
    - time meteor build . --server-only;
    - time find $PROJECTFOLDER -mindepth 1 -delete;
    - time rsync -av $PROJECTFILE $PROJECTFOLDER;
    - cd $PROJECTFOLDER && tar -xf $PROJECTFILE && cd bundle/programs/server && meteor npm install --production && chown -R $PROJECTUSER:www-data . && passenger-config restart-app $PROJECTFOLDER;
